#!/usr/bin/env python3
"""Generate the permission matrix from the chaincode, not by hand.

Table 2 of the manuscript is the deployed authorization policy.  Writing it
out by hand is how it came to disagree with `chaincode/hrbac/roles.go`, so it
is parsed from the Go source instead and emitted as a LaTeX table.

Run:  python3 analysis/derive_policy_table.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROLES_GO = ROOT / "chaincode" / "hrbac" / "roles.go"
OUT = ROOT / "paper_iot" / "tables" / "tab_permissions.tex"

ROLE_ORDER = ["Sensor", "Gateway", "Farmer", "Agronomist", "Certifier",
              "SupplyChain", "Admin"]
PERM_ORDER = ["ReadOwn", "ReadZone", "ReadAll", "WriteSensor", "ControlZone",
              "ControlAll", "ReadAudit", "IssueCrossZone", "ManageRoles",
              "AdminAll"]
PERM_LABEL = {
    "ReadOwn": "Read own", "ReadZone": "Read zone", "ReadAll": "Read all",
    "WriteSensor": "Write sensor", "ControlZone": "Control zone",
    "ControlAll": "Control all", "ReadAudit": "Read audit",
    "IssueCrossZone": "Issue CZT", "ManageRoles": "Manage roles",
    "AdminAll": "Admin all",
}


def parse_map(source: str, name: str) -> dict[str, list[str]]:
    block = re.search(rf"var {name} = map\[Role\]\[\]\w+\{{(.*?)\n\}}",
                      source, re.S)
    if not block:
        sys.exit(f"could not find {name} in {ROLES_GO}")
    out: dict[str, list[str]] = {}
    for role, items in re.findall(r"(\w+):\s*\{([^}]*)\}", block.group(1)):
        out[role] = [x.strip() for x in items.split(",") if x.strip()]
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=OUT,
                        help="destination for the generated table")
    args = parser.parse_args()

    source = ROLES_GO.read_text()
    direct = parse_map(source, "rolePermissions")
    ancestors = parse_map(source, "roleAncestors")

    effective = {
        role: {p for a in ancestors.get(role, [role]) for p in direct.get(a, [])}
        for role in ROLE_ORDER
    }

    header = " & ".join(["Permission"] + [
        r.replace("SupplyChain", "Supply") for r in ROLE_ORDER]) + r" \\"
    body = []
    for perm in PERM_ORDER:
        cells = [r"\ding{51}" if perm in effective[r] else "--"
                 for r in ROLE_ORDER]
        body.append(f"{PERM_LABEL[perm]} & " + " & ".join(cells) + r" \\")

    lines = [
        "%% AUTO-GENERATED by analysis/derive_policy_table.py from",
        "%% chaincode/hrbac/roles.go -- do not edit.",
        r"\begin{widetab}",
        r"\centering",
        r"\caption{Effective permissions per role, generated from the deployed"
        r" chaincode (\texttt{roles.go}) rather than transcribed. Inheritance"
        r" along the human chain (SupplyChain to Certifier to Agronomist to"
        r" Farmer to Admin) is why \emph{Read audit} reaches Agronomist and"
        r" Farmer.}",
        r"\label{tab:permissions}",
        r"\small",
        r"\begin{tabularx}{\linewidth}{@{}l*{7}{C}@{}}",
        r"\toprule",
        header,
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabularx}",
        r"\end{widetab}",
    ]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")
    for role in ROLE_ORDER:
        print(f"  {role:12s} {sorted(effective[role])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
